version: '3.1'
services:
  springboot:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    container_name: springboot-api-camara-vereadores
    image: api-camara-vereadores
    ports:
      - '8080:8080'
      - '5005:5005'
    links:
      - mysql
      
  mysql:
    container_name: mysql-api-camara-vereadores
    image: mysql:8.0
    volumes:
      - ./docker/mysql/volume_api_camara_vereaderes_dev_db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=api_camara_vereadores_dev_db
      - MYSQL_USER=api_camara_vereadores_dev_root
      - MYSQL_PASSWORD=api_camara_vereadores_dev_pw
      - MYSQL_ROOT_PASSWORD=api_camara_vereadores_dev_pw
    ports:
      - "3306:3306"