version: '3.1'
services:
  springboot:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    container_name: springboot-api-camara-vereadores
    image: api-camara-vereadores
    ports:
      - '8080:8080'
      - '5005:5005'