version: '3.8'
services:
#   springboot:
#     build: 
#       context: ./
#       dockerfile: ./Dockerfile
#     container_name: springboot-api-camara-vereadores
#     image: api-camara-vereadores
#     ports:
#       - '8080:8080'
#       - '5005:5005'

  jenkins:
    container_name: jenkins-camara-vereadores
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 2000:8080
      - 50000:50000
    volumes:
      - ./docker/storage/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_configuration: